[build]
  command = "composer install --no-dev --optimize-autoloader && npm install && npm run build"
  publish = "public"

[build.environment]
  PHP_VERSION = "8.2"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
